export const calculators = [
  {
    id: "sip",
    name: "SIP Calculator",
    description: "Your path to smart investing.",
    inputs: [
      { label: "Monthly Investment (₹)", key: "investment", type: "number", default: 5000, max: 1000000 },
      { label: "Expected Return Rate (%)", key: "rate", type: "number", default: 12, max: 30 },
      { label: "Investment Duration (Years)", key: "time", type: "number", default: 10, max: 40 },
    ],
    output: "Future Value (₹)",
  },
    {
      id: "lumpsum",
      name: "Lumpsum Calculator",
      description: "Calculate the future value of a lumpsum investment.",
      inputs: [
        { label: "Investment Amount (₹)", key: "investment", type: "number",default: 5000, max: 100000 },
        { label: "Expected Return Rate (%)", key: "rate", type: "number", default: 12, max: 30},
        { label: "Investment Duration (Years)", key: "time", type: "number", default: 10, max: 40  },
      ],
      output: "Future Value (₹)",
    },
    {
      id: "mutualFund",
      name: "Mutual Fund Calculator",
      description: "Estimate returns for mutual fund investments.",
      inputs: [
        { label: "Investment Amount (₹)", key: "investment", type: "number",default: 5000, max: 100000 },
        { label: "Expected Return Rate (%)", key: "rate", type: "number", default: 12, max: 30 },
        { label: "Duration (Years)", key: "time", type: "number", default: 10, max: 40  },
      ],
      output: "Maturity Value (₹)",
    },
    {
      id: "ppf",
      name: "PPF Calculator",
      description: "Calculate the maturity value of a PPF investment.",
      inputs: [
        { label: "Yearly Investment (₹)", key: "investment", type: "number",default: 5000, max: 100000 },
        { label: "Investment Duration (Years)", key: "time", default: 10, max: 40  },
        { label: "Interest Rate (%)", key: "rate", type: "number", default: 12, max: 30 },
      ],
      output: "Maturity Value (₹)",
    },
    {
      id: "epf",
      name: "EPF Calculator",
      description: "Calculate EPF corpus at retirement.",
      inputs: [
        { label: "Monthly Basic Salary (₹)", key: "basicSalary", type: "number",default:50000 , max:500000   },
        { label: "Employer Contribution (%)", key: "employerRate", type: "number" ,default:30 , max:30   },
        { label: "Employee Contribution (%)", key: "employeeRate", type: "number",default:30 , max:  30  },
        { label: "Interest Rate (%)", key: "rate", type: "number",default: 12, max:  20  },
        { label: "Working Years", key: "time", type: "number",default:5 , max:  40  },
      ],
      output: "EPF Corpus (₹)",
    },
    {
      id: "rd",
      name: "Recurring Deposit (RD) Calculator",
      description: "Calculate the maturity value of a recurring deposit.",
      inputs: [
        { label: "Monthly Deposit (₹)", key: "investment", type: "number",default:50000 ,max: 1000000 },
        { label: "Interest Rate (%)", key: "rate", type: "number",default:7 ,max:15 },
        { label: "Duration (Months)", key: "time", type: "number",default:3,max:10 },
      ],
      output: "Maturity Value (₹)",
    },
    {
      id: "fd",
      name: "Fixed Deposit (FD) Calculator",
      description: "Calculate the maturity value of a fixed deposit.",
      inputs: [
        { label: "Deposit Amount (₹)", key: "investment", type: "number",default:50000 ,max: 1000000 },
        { label: "Interest Rate (%)", key: "rate", type: "number",default:7 ,max:15 },
        { label: "Duration (Years)", key: "time", type: "number",default:3,max:10 },
      ],
      output: "Maturity Value (₹)",
    },
    {
      id: "nps",
      name: "NPS Calculator",
      description: "Calculate NPS corpus and monthly pension.",
      inputs: [
        { label: "Monthly Contribution (₹)", key: "investment", type: "number", default: 5000, max: 100000 },
        { label: "Investment Duration (Years)", key: "time", type: "number", default: 20, max: 60 },
        { label: "Return Rate (%)", key: "rate", type: "number", default: 8, max: 15 },
        { label: "Annuity Rate (%)", key: "annuityRate", type: "number", default: 6, max: 10 },
      ],
      output: "Corpus & Pension (₹)",
    },
    {
      id: "retirement",
      name: "Retirement Calculator",
      description: "Estimate retirement corpus required.",
      inputs: [
        { label: "Monthly Expenses (₹)", key: "expenses", type: "number", default: 30000, max: 200000 },
        { label: "Years Until Retirement", key: "yearsToRetire", type: "number", default: 20, max: 40 },
        { label: "Post-Retirement Years", key: "postRetirementYears", type: "number", default: 25, max: 40 },
        { label: "Inflation Rate (%)", key: "inflationRate", type: "number", default: 6, max: 10 },
        { label: "Return Rate (%)", key: "rate", type: "number", default: 8, max: 15 },
      ],
      output: "Retirement Corpus (₹)",
    },
    {
      id: "emi",
      name: "EMI Calculator",
      description: "Calculate your loan EMI.",
      inputs: [
        { label: "Loan Amount (₹)", key: "principal", type: "number", default: 1000000, max: 100000000 },
        { label: "Interest Rate (%)", key: "rate", type: "number", default: 8, max: 15 },
        { label: "Loan Tenure (Years)", key: "time", type: "number", default: 15, max: 30 },
      ],
      output: "Monthly EMI (₹)",
    },
    {
      id: "carLoan",
      name: "Car Loan EMI Calculator",
      description: "Calculate EMI for your car loan.",
      inputs: [
        { label: "Car Loan Amount (₹)", key: "principal", type: "number", default: 500000, max: 5000000 },
        { label: "Interest Rate (%)", key: "rate", type: "number", default: 8, max: 15 },
        { label: "Loan Tenure (Years)", key: "time", type: "number", default: 5, max: 7 },
      ],
      output: "Monthly EMI (₹)",
    },
    {
      id: "homeLoan",
      name: "Home Loan EMI Calculator",
      description: "Calculate EMI for your home loan.",
      inputs: [
        { label: "Home Loan Amount (₹)", key: "principal", type: "number", default: 3000000, max: 100000000 },
        { label: "Interest Rate (%)", key: "rate", type: "number", default: 8, max: 15 },
        { label: "Loan Tenure (Years)", key: "time", type: "number", default: 20, max: 30 },
      ],
      output: "Monthly EMI (₹)",
    },
    {
      id: "stepUpSip",
      name: "Step-up SIP Calculator",
      description: "Calculate the future value of a step-up SIP investment.",
      inputs: [
        { label: "Initial Monthly Investment (₹)", key: "initialInvestment", type: "number", default: 5000, max: 50000 },
        { label: "Step-up Percentage (%)", key: "stepUpRate", type: "number", default: 10, max: 20 },
        { label: "Expected Return Rate (%)", key: "rate", type: "number", default: 12, max: 20 },
        { label: "Investment Duration (Years)", key: "time", type: "number", default: 15, max: 30 },
      ],
      output: "Future Value (₹)",
    },
    {
      id: "incomeTax",
      name: "Income Tax Calculator",
      description: "Estimate your income tax liability.",
      inputs: [
        { label: "Annual Income (₹)", key: "income", type: "number", default: 600000, max: 50000000 },
        { label: "Deductions (₹)", key: "deductions", type: "number", default: 150000, max: 500000 },
      ],
      output: "Tax Payable (₹)",
    },
    {
      id: "interestRateComparison",
      name: "Flat vs Reducing Interest Rate Calculator",
      description: "Compare flat and reducing interest rates.",
      inputs: [
        { label: "Loan Amount (₹)", key: "principal", type: "number", default: 1000000, max: 100000000 },
        { label: "Flat Interest Rate (%)", key: "flatRate", type: "number", default: 8, max: 15 },
        { label: "Reducing Interest Rate (%)", key: "reducingRate", type: "number", default: 8, max: 15 },
        { label: "Loan Tenure (Years)", key: "time", type: "number", default: 10, max: 30 },
      ],
      output: "Comparison Results",
    },
    {
      id: "brokerage",
      name: "Brokerage Calculator",
      description: "Calculate brokerage charges for trading.",
      inputs: [
        { label: "Transaction Amount (₹)", key: "transactionAmount", type: "number", default: 100000, max: 5000000 },
        { label: "Brokerage Rate (%)", key: "brokerageRate", type: "number", default: 0.5, max: 2 },
        { label: "Taxes & Other Charges (%)", key: "taxes", type: "number", default: 0.2, max: 1 },
      ],
      output: "Total Charges (₹)",
    },
    {
      id: "margin",
      name: "Margin Calculator",
      description: "Calculate margin required for trading.",
      inputs: [
        { label: "Trade Value (₹)", key: "tradeValue", type: "number", default: 100000, max: 5000000 },
        { label: "Leverage Factor", key: "leverage", type: "number", default: 10, max: 20 },
      ],
      output: "Margin Required (₹)",
    },
    {
      id: "inflation",
      name: "Inflation Calculator",
      description: "Estimate future value adjusted for inflation.",
      inputs: [
        { label: "Current Amount (₹)", key: "currentAmount", type: "number", default: 100000, max: 10000000 },
        { label: "Inflation Rate (%)", key: "inflationRate", type: "number", default: 6, max: 10 },
        { label: "Time Period (Years)", key: "time", type: "number", default: 10, max: 50 },
      ],
      output: "Future Value (₹)",
    },
    {
      id: "stockAverage",
      name: "Stock Average Calculator",
      description: "Calculate the average price of stock holdings.",
      inputs: [
        { label: "Shares Bought (First Purchase)", key: "shares1", type: "number", default: 100, max: 1000 },
        { label: "Price per Share (₹)", key: "price1", type: "number", default: 500, max: 10000 },
        { label: "Shares Bought (Second Purchase)", key: "shares2", type: "number", default: 100, max: 1000 },
        { label: "Price per Share (₹)", key: "price2", type: "number", default: 500, max: 10000 },
      ],
      output: "Average Price per Share (₹)",
    },
    
  ];
  